- name: Add PPA for gcc 4.9
  become: yes
  become_user: root
  apt_repository:
    repo: 'ppa:ubuntu-toolchain-r/test'
  tags:
    - pyfr

- name: Install pip3
  apt: name={{ item }} state=present update_cache=yes
  become: yes
  become_user: root
  with_items:
    - python3-pip
  tags:
    - pyfr

- name: Install required native libs
  apt: name={{ item }} state=present
  become: yes
  become_user: root
  with_items:
    - libhdf5-dev
    - cython3
    - libmpich-dev
    - libmetis-dev
    - libopenblas-dev
    - git
    - g++-4.9
  tags:
    - pyfr

- name: Update alternatives to use gcc 4.9
  become: yes
  become_user: root
  alternatives:
    name: gcc
    path: /usr/bin/gcc-4.9
    link: /usr/bin/gcc
  tags:
    - pyfr

- name: Install PyFR required packages
  pip: executable=pip3  name={{item.package}} version={{item.version}} state=present
  become: yes
  become_user: root
  with_items:
    - {package: 'numpy', version: 1.11.0}
    - {package: 'six', version: 1.8.0}
  tags: pyfr

- name: Install pycuda
  pip: executable=pip3  name=pycuda state=present
  become: yes
  become_user: root
  when: install_pycuda
  tags: pyfr

- name: Install PyFR from GitHub
  pip: executable=pip3 name="git+https://github.com/vincentlab/PyFR.git@{{ pyfr_version }}#egg=pyfr" state=present editable=False
  become: yes
  become_user: root
  tags: pyfr
